sudo: false
dist: trusty
language: node_js
notifications:
  email: false
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    
node_js:
- '6.9'
matrix:
  fast_finish: true
before_install:
- export CHROME_BIN=chromium-browser
- npm install -g npm@5.3
- npm install -g @angular/cli
- npm install -g snyk
- npm cache verify
- npm prune
- npm update
install:
- npm install
- snyk protect
- snyk auth SNYK_TOKEN
- snyk test
after_install:
- npm rebuild node-sass
- ./node_modules/protractor/bin/webdriver-manager update
before_script:
- npm rebuild node-sass
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- npm run continuous-integration
deploy:
  provider: heroku
  api_key:
    secure: e/wAaYe0WzTkznvqAT2asLDZ+QEusaY+DYe2nkMgchDi82ipc3lHRxRewb32cSTTFTn9TtdGAobLnw+xJvb1BMMkipBpPkDmCU29LaGVDrDWrn3FvMHFZMUOCm5Oq29kowmGkjLWD68afZMbNdkX5BM6HXSOa6AAXE0tKf/DyjoN8kHDOc1Rb2u40NDkYisTrzjtcjJOuM+/NnfyUfRA4BI5OgSBt8wiWrWhbrAQcK0wYQL8knYaYL7xlAQwQAcV0j3NYuKIH4h/IfnYQVavBL95w4w26U8hLGilzBeEFUmhSU8MbJyYPJMJiXGywIubypf8Diz+tqc0Z5LQ/JRxDAAGVKOhdoH2lxUGODHMlpMVulCD1DLC/HFk8oPv/kY/gkMF2de4zpmgzSausSGPxn+H4XCbTU2Ea6jN0A8smYTPehf7Pj4TsYDByMT3wBl3gANQLn1OkPVRPXr76zjOXAUo2m3IDm/06KjPD2hkEdUKki7FDzdgZMAceEGgHq9DeZc+ATzRh5nsrLiH6LHykJHCImLSndqH6P/7N8rqgyVyDBoV1QkIL6Jr3LGKwiPkGz8llEZTqcBN9zSzjoYngGHnDxrJPIIzysD2stkYrhTZo6ATCi8XxV1tdCJWVhZWCKC+SCe63IgvYiWegLeAoeYojzuE6tbdDq8V0RY+oPg=
  app: zack-social-network
  on:
    condition: all_branches
after_deploy:
- snyk monitor